### DISCUSSION TITLE
How to use one domain for both excalidraw and excalidraw-room?

### DISCUSSION THREAD

**Discussion by matrixes** [excalidraw/excalidraw#8835] [Q&A]
This is one fantastic web app, I'm making much use of it.

That said, I'm stuck in setting up an Nginx reverse proxy -> docker stack where I use only one host domain name, e.g. excalidraw.example.com.

It's simple enough
![image](https://github.com/user-attachments/assets/060f88bd-a471-488b-9a6c-e55fea3fdf63)

I'd like for visitors to hit https://excalidraw.example.com to access Excalidraw. But, I'd also like visitors to be able to use the collaboration feature.
I have set up a docker-compose stack that looks like this:

```
version: "3.8"

services:
  excalidraw:
    build:
      context: ./excalidraw
      args:
        - NODE_ENV=production
    container_name: excalidraw
    ports:
      - "3333:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules
    
  excalidraw-room:
    build:
      context: ./excalidraw-room
    environment:
      # Collaboration WebSocket
      PORT: 3002
    ports:
      - "4444:3002"

volumes:
  notused:
```

This is fairly standard configuration as far as I've been able to gather.

The Nginx revers-proxy looks like the following:

```
server {
    server_name excalidraw.example.com;
    ...
    location / {
        proxy_pass http://192.168.1.10:3333;
    }

    location /ws/ {
        # Web sockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_pass http://192.168.1.10:4444/;
        #return 200 'gangnam style!';
    }
```

The .env.production-file for Excalidraw looks like the following:

```
...
# socket server URL used for collaboration
VITE_APP_WS_SERVER_URL=https://excalidraw.example.com/ws
...
```

When starting a collaboration session with this setup, there's an error in the output in the console log

```
wss://excalidraw.example.com/socket.io/?EIO=4&transport=websocket
```

As you can see, the log states `wss://excalidraw.example.com/` but it's totally omitting the "/ws" that I have put in .env.production.

I have only been able to solve this situation by creating another subdomain, e.g. "excalidraw-room.example.com" and point `VITE_APP_WS_SERVER_URL` to that, but I'd much rather have one host delivering both services.

I can't for the life of me figure out why this is an issue. I'm just finding it hard to believe this isn't a thing that can be set up this way (without e.g. recoding large parts of the app).
