### ISSUE TITLE
Theme style variables are not applied in Codesandbox

### ISSUE THREAD

**Issue by yongdamsh** [excalidraw/excalidraw#1346]
The style variables below are not reflected because [Codesandbox](https://codesandbox.io/s/github/excalidraw/excalidraw) does not properly import the 'theme.css' file. 

```css
:root {
  --text-color-primary: #343a40;
  --bg-color-main: #fff;
  --shadow-island: 0 1px 5px rgba(0, 0, 0, 0.15);
  --border-radius-m: 4px;
  --space-factor: 0.25rem;
}
```

This can be solved by changing the 'theme.css' file extension to scss. But it would be better if we could report an issue to Codesandbox to see if it could be solved. Or is there a root cause?

<img width="936" alt="스크린샷 2020-04-10 오전 1 54 30" src="https://user-images.githubusercontent.com/4126644/78921474-ec547b80-7acf-11ea-915d-8ae34458bb6c.png">
<img width="672" alt="스크린샷 2020-04-10 오전 1 54 39" src="https://user-images.githubusercontent.com/4126644/78921482-f0809900-7acf-11ea-862e-0f9a1d1e1275.png">
