### ISSUE TITLE
Fonts do not load when SVGs are embedded in GitHub markdown

### ISSUE THREAD

**Issue by disintegrator** [excalidraw/excalidraw#4855]
GitHub's content security policy blocks loading Excalidraw's fonts when loading SVG files from raw.githubusercontent.com. 
Similarly, when viewing markdown files with svg images embedded in `img` tags, the fonts are also not rendering. Although in this case, it is not related to CSP but it is by [design](https://css-tricks.com/using-custom-fonts-with-svg-in-an-image-tag/#aa-the-image-tag). In both cases, the browser fallsback to rendering Times font on macOS 11.6 + Firefox 97.

 
 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/678548/156169307-998f84fe-be83-4fee-be19-7e5a5926923a.png">

**Comment by zsviczian** [comment]
![Scratch Pad 2](https://user-images.githubusercontent.com/14358394/156208312-62c8c33b-c76f-481b-abd0-ed53c580bebc.svg)
[fonts.zip](https://github.com/excalidraw/excalidraw/files/8163155/fonts.zip)

I've implemented the feature to add the font definitions the the SVG file in the Obsidian-Excalidraw implementation, but you can simply add the two base64 font definitions in styles manually, following the attached example.

**Comment by michalfita** [comment]
I would be interested in this fix, as when the scribbling font is not displayed by GitHub, diagrams look nasty.

**Comment by karlhorky** [comment]
@zsviczian that's a cool fix! Do you have a script that adds this to fix Excalidraw SVGs?

🤔 I guess it wouldn't be difficult to write such a script... just `.replace()` on these with the inline base64 version like you provided above.

```svg
  <defs>
    <style class="style-fonts">
      @font-face {
        font-family: "Virgil";
        src: url("https://excalidraw.com/Virgil.woff2");
      }
      @font-face {
        font-family: "Cascadia";
        src: url("https://excalidraw.com/Cascadia.woff2");
      }
    </style>
  </defs>
```

**Comment by karlhorky** [comment]
Another workaround would be to use a fallback font stack (available on Windows, macOS and Linux) for each of the two 

```diff
<text
  x="0"
  y="0"
- font-family="Cascadia, Segoe UI Emoji"
+ font-family="Cascadia, ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace, Segoe UI Emoji"
  font-size="20px"
  fill="#ff7575"
  text-anchor="start"
  style="white-space: pre;"
  direction="ltr"
  dominant-baseline="text-before-edge"
>courses</text>
```

Maybe this should be a PR actually...

**Comment by karlhorky** [comment]
### Workaround 3

Use a GitHub Actions workflow like this to find and replace all `font-family`s in all Excalidraw SVG files based on [these fallbacks](https://github.com/excalidraw/excalidraw/pull/6479) (you'll need to set up a secret `EXCALIDRAW_SVG_FONT_FIX_TOKEN` with a token that has write access to the repository):

`.github/workflows/fix-excalidraw-svg-fonts.yml`

```yml
# 
name: Compress PDFs
on:
  pull_request:
    # Run only when Excalidraw SVG files are added or changed
    paths:
      - '**.excalidraw.svg'

jobs:
  build:
    # Only run on Pull Requests within the same repository, and not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Fix Excalidraw SVG Fonts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Fix fonts in Excalidraw SVGs
        run: |
          find . -type f -iname '*.excalidraw.svg' | while read file; do
            echo "Fixing fonts in $file"
            sed -i 's/Virgil, Segoe UI Emoji/Virgil, "Comic Sans MS", "Segoe Print", "Bradley Hand", "Lucida Handwriting", "Marker Felt", cursive/g' "$file"
            sed -i 's/Helvetica, Segoe UI Emoji/Helvetica, -apple-system,BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"/g' "$file"
            sed -i 's/Cascadia, Segoe UI Emoji/Cascadia, ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace, Segoe UI Emoji/g' "$file"
          done
      - name: Commit files
        run: |
          git config user.email github-actions[bot]@users.noreply.github.com
          git config user.name github-actions[bot]

          git add **/*.excalidraw.svg
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "Fix fonts in Excalidraw SVGs"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.EXCALIDRAW_SVG_FONT_FIX_TOKEN }}
```
