### ISSUE TITLE
I want to have self-host server.

### ISSUE THREAD

**Issue by jingesky** [excalidraw/excalidraw#5188]
Hello everybody.
Thank you for your great project.
When can I have a self-host server project where collaboration is enabled?

**Comment by ad1992** [comment]
Hi @jingesky 👋🏻, sorry for the delayed response.
You will need to clone [excalidraw-room](https://github.com/excalidraw/excalidraw-room) and host the server yourself.,  also you will need to clone [excalidraw](https://github.com/excalidraw/excalidraw) and update the `env` variables `REACT_APP_WS_SERVER_URL` in your `.env` files
However if you are looking for integrating npm package with collaboration then you can check [this](https://github.com/excalidraw/excalidraw/discussions/3879)

**Comment by artemanufrij** [comment]
@ad1992 

It seems to be broken. Own instance still try to connect to portal.excalidraw.com
![Screenshot_20221210_122803](https://user-images.githubusercontent.com/16517095/206852974-42faa52b-38d2-435e-bfdb-31bbe99346ac.png)

.env
```
REACT_APP_LIBRARY_URL=https://libraries.excalidraw.com

REACT_APP_WS_SERVER_URL=http://excalidraw-room:3002

REACT_APP_PORTAL_URL=
```

docker-compose.yml
```yml
version: "3"

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    restart: always
    ports:
      - "8084:80"
    depends_on:
      - excalidraw-room
    env_file: .env

  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
```

**Comment by sebw** [comment]
Same problem here. The env var seems to be ignored.

**Comment by ad1992** [comment]
@sebw @artemanufrij probably the file is getting overridden with `.env.production` can you try setting `REACT_APP_WS_SERVER_URL` in  `.env.local` and check ?

**Comment by sebw** [comment]
I just do a `docker run` and pass env to the CLI without an env file. A `docker inspect` shows the correct value for `REACT_APP_WS_SERVER_URL` and if I `sh` inside the container, env gives the correct value as well.

**Comment by xotaki** [comment]
@artemanufrij @sebw 
After modifying .env file, you need to build the container again.
```
$ podman build -t excalidraw/excalidraw .
```

**Comment by l4rm4nd** [comment]
Ok, it seems we can easily fix it.

Without cloning repos and building the images manually.

We can just define a custom entrypoint for the excalidraw container and overwrite the already built JS assets at `/usr/share/nginx/html/assets` with our custom excalidraw-room url taken from the env `VITE_APP_WS_SERVER_URL`. 

Here a working example using Traefik as reverse proxy:

````yaml
services:

  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    expose:
      - 80
    restart: unless-stopped
    entrypoint: /bin/sh
    command:
      - -c
      - |
        echo "Replacing WebSocket URL with: $$VITE_APP_WS_SERVER_URL"
        find /usr/share/nginx/html/assets -type f -name "*.js" -exec sed -i 's|https://oss-collab\.excalidraw\.com|'$$VITE_APP_WS_SERVER_URL'|g' {} +
        echo "Starting nginx..."
        nginx -g 'daemon off;'
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:80/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s    
    environment:
      - NODE_ENV=production
      - VITE_APP_WS_SERVER_URL=https://draw2gether.example.com
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw.rule=Host(`draw.example.com`)
      - traefik.http.services.excalidraw.loadbalancer.server.port=80
      - traefik.docker.network=proxy

  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    container_name: excalidraw-room
    expose:
      - 80
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:80/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw-collab.rule=Host(`draw2gether.example.com`)
      - traefik.http.services.excalidraw-collab.loadbalancer.server.port=80
      - traefik.docker.network=proxy

networks:
  proxy:
   external: true
````

>[!CAUTION]
> HTTPS is required due to browser security. Otherwise, collaboration will not work.
> Use a reverse proxy and issue proper SSL certificates.

Afterwards, collaborations works fine.

Just browse `https://draw.example.com` and trigger the `Live collaboration` from the hamburger menu. Share the link and if another person opens it, a new session will occur. Visible at the top right (people icon) as well as interactive mouse pointer with the person's name.

<img width="1166" height="537" alt="Image" src="https://github.com/user-attachments/assets/977c9216-a861-4b05-88bb-07fac76ba787" />

Blog post: https://blog.lrvt.de/selfhosting-excalidraw-with-collaboration-support/
