### ISSUE TITLE
[bug] Obsidian + Dark theme: Menu items unreadable

### ISSUE THREAD

**Issue by replete** [excalidraw/excalidraw#6341]
(amazing plugin, thank you kindly)

# Bug Report:

When using a dark theme in Obsidian (I use 'minimal theme' and a hotkey to switch between light/dark) some UI elements are not readable in dark mode, and also `:hover` backgrounds are incorrect.

## Environment:
- MacOS 13.2.1
- Obsidian 1.1.16 (1.1.15 installer)
- Minimal Theme 6.3.2

## Screenshot

![Screenshot 2023-03-09 at 13 38 27](https://user-images.githubusercontent.com/812139/224039783-a6cc8d05-5336-4b77-9e2b-2b14a33dc832.png)

## Fix / Kludge

![Screenshot 2023-03-09 at 13 41 55](https://user-images.githubusercontent.com/812139/224041685-4714dba4-5b92-48ed-b77f-70b12767943c.png)

I wrote a [CSS snippet](https://github.com/replete/obsidian-minimal-theme-css-snippets/blob/main/%5Bplugin%5D%20Excalidraw.css) to fix it:

```css
/*
    Excalidraw plugin fixes
    https://github.com/replete/obsidian-minimal-theme-css-snippets
*/

/* app toolbar menu item color for dark themes */
.theme-dark .excalidraw .App-toolbar .dropdown-menu-item  {
    color:hsl( var(--base-h),var(--base-s), calc(var(--base-l) + 70%) ) !important;

}

/* toolbar background for dark themes */
.theme-dark .excalidraw .ToolIcon .ToolIcon__icon:hover,
.theme-dark .excalidraw .dropdown-menu-button:hover,
.theme-dark .excalidraw .library-button:hover {
    background-color:hsl( var(--base-h),var(--base-s), calc(var(--base-l) + 15%) ) !important;
} 
```
* variables like `var(--tx1)` seemed to be overridden, so I calculated a more sensible value using `hsl()`, its a hack but does the job for me
