### ISSUE TITLE
Collaboration-Room (TUTO)

### ISSUE THREAD

**Issue by siddjellali** [excalidraw/excalidraw#6506]
Hi, 

I finally achieve to work with collaboration container (excalidraw-room).  :rocket: 
Please find below my docker compose (with RP: traefik).
Note that the websocket HAVE to be on another URL (not a PATH - It doesn't work), if you go through ReverseProxy as traefik. 

```
---
version: "3.7"
########################### NETWORKS
networks:
  t2_proxy:
    external: true
########################### VOLUMES
volumes:
  notused:
    driver: local
########################### SERVICES
services:
  excalidraw-server:
    image: xxxxxxxxxxxxx/excalidraw:latest (custom, build your own)
    restart: always
    networks:
      t2_proxy:
    volumes:
      - notused:/opt/node_app/app/node_modules
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.excalidraw.entrypoints=https"
      - "traefik.http.routers.excalidraw.rule=Host(`draw.EXAMPLE.com`)"
      ## HTTP Services
      - "traefik.http.routers.excalidraw.service=excalidraw-svc"
      - "traefik.http.services.excalidraw-svc.loadbalancer.server.scheme=http"
      - "traefik.http.services.excalidraw-svc.loadbalancer.server.port=80"
      - "traefik.http.routers.excalidraw.tls=true"
      - "traefik.http.routers.excalidraw.tls.certresolver=xxxxxxxxxx"

  excalidraw-room:
    image: excalidraw/excalidraw-room:latest (official)
    restart: always
    networks:
      t2_proxy:
    environment:
      TZ: Europe/Paris
      PORT: 3002
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.excaliroom.entrypoints=https"
      - "traefik.http.routers.excaliroom.rule=Host(`draw-ws.EXAMPLE.com`)"
      ## HTTP Services
      - "traefik.http.routers.excaliroom.service=excaliroom-svc"
      - "traefik.http.services.excaliroom-svc.loadbalancer.server.scheme=http"
      - "traefik.http.services.excaliroom-svc.loadbalancer.server.port=3002"
      - "traefik.http.routers.excaliroom.tls=true"
      - "traefik.http.routers.excaliroom.tls.certresolver=xxxxxxxxxxxxxx"
      - "traefik.http.routers.excaliroom.middlewares=websocket"
      - "traefik.http.middlewares.websocket.headers.customrequestheaders.X-Forwarded-Proto=https"
```

**My Dockerfile for Excalidraw** 

```
FROM node:14-alpine AS download
WORKDIR /opt/node_app
# Télcharger une version de Excalidraw
RUN wget https://github.com/excalidraw/excalidraw/archive/refs/tags/v0.15.0.tar.gz -O excalidraw.tar.gz
RUN tar -zvxf excalidraw.tar.gz
RUN mv excalidraw-* excalidraw

FROM node:14-alpine AS build

ENV PUB_SRV_NAME draw.EXAMPLE.com
ENV PUB_SRV_NAME_WS draw-ws.EXAMPLE.com
ENV NODE_ENV development
ENV TZ Europe/Paris
ENV REACT_APP_BACKEND_V2_GET_URL https://$PUB_SRV_NAME/api/v2/
ENV REACT_APP_BACKEND_V2_POST_URL https://$PUB_SRV_NAME/api/v2/post
ENV REACT_APP_WS_SERVER_URL https://$PUB_SRV_NAME_WS/

WORKDIR /opt/node_app

COPY --from=download /opt/node_app/excalidraw/package.json /opt/node_app/excalidraw/yarn.lock ./
RUN yarn --ignore-optional --network-timeout 600000

COPY --from=download /opt/node_app/excalidraw/ .
RUN yarn build:app:docker

FROM nginx:1.21-alpine

COPY --from=build /opt/node_app/build /usr/share/nginx/html

HEALTHCHECK CMD wget -q -O /dev/null http://localhost || exit 1
```

I hope this can help other people <3

**Comment by eric-schleicher** [comment]
Thanks, i think i sort of got it working with your example.  I created this additional service entry for traefik to get it up, but i seem to be having issues with the synchronization.  on page reloads collaboration will be synced, but not on an ongoing basis.  


```
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=youmail@yourdomain.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/user/docker_home/traefik/letsencrypt:/letsencrypt"
    networks:
      - t2_proxy
```

interest to know if I'm doing it wrong :P
