### ISSUE TITLE
Publishing the container image with tags in addition to "latest"

### ISSUE THREAD

**Issue by johanneskastl** [excalidraw/excalidraw#8122]
Would it be possible to publish the container image with tags in addition to just `latest`?

Either using the version of excalidraw that is included or just a date (20240611)? That would allow referring to the image versions without using the full-fledged sha256sum hash...

I daresay this needs just some little tweaks to the workflow:
https://github.com/excalidraw/excalidraw/blob/master/.github/workflows/publish-docker.yml#L25

There is an action that does a lot of the heavy lifting and collects the metadata:

```
      # This step uses
      # [docker/metadata-action](https://github.com/docker/metadata-action#about)
      # to extract tags and labels that will be applied to the specified image.
      # The `id` "meta" allows the output of this step to be referenced in a
      # subsequent step. The `images` value provides the base name for the tags
      # and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
```

https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

Kind Regards,
Johannes
