### ISSUE TITLE
feat: Search library, Resize library pane and objects

### ISSUE THREAD

**Issue by sammcj** [excalidraw/excalidraw#8304]
The library is _really_ hard to navigate and find what you're looking for.

It would be great if the library had a search box at the top so you could enter something like "postgres" and have any matching items brought to the top.

Additionally the side pane with the library is _really_ small both in frame size and object size compared to the rest of excalidraw - this means you end up scrolling vertically for a long time and squinting to see what the items are. Perhaps this could be a resizable pane and respect cmd++/- to scale the items?

**Comment by Josh5A** [comment]
YES please. 

Check out how SketchWow integrates this, attached is a screenshot of searching for "robot" – all the matches show at the top of the library list
![image](https://github.com/user-attachments/assets/de0997a6-6eb0-4659-a7c1-2ca7f2fc9e1c)

**Comment by Jamish** [comment]
+1. I used to be able to Command+F to at least search for text in my library, but now that shortcut is commandeered by the in-app search bar. I have to go to Edit > Find in Page in my browser menu in order to search my library, which is a drag.

This is currently my biggest feature wish for Excalidraw.

**Comment by guillaume-gc** [comment]
+1.

This is my biggest pain point with Excalidraw, especially since, as pointed out by Jamish, you cannot use Command+F to search text anymore.

**Comment by mistapetroz** [comment]
+1000
Just a heads-up: this was actually tackled in [PR #6549](https://github.com/excalidraw/excalidraw/pull/6549) by [Hendrik](https://github.com/henobi) last year. Thought I’d resurface it here for visibility and consideration.

**Comment by AlessandroVol23** [comment]
Any update on that? I think this PR https://github.com/excalidraw/excalidraw/pull/6549 tackled exactly that but it is pretty stale. 
I'd love to have this feature!

**Comment by giselle197** [comment]
For larger library pane and objects

I use DevTools to see the original css styles and try to adjust them.
(I commented out the original lines where I modified)

```css
.excalidraw .sidebar {
    background-color: var(--sidebar-bg-color);
    border-left: 1px solid var(--sidebar-border-color);
    border-radius: 0;
    bottom: 0;
    box-shadow: var(--sidebar-shadow);
    box-sizing: border-box;
    display: flex;
    flex-direction: column;
    margin: 0;
    overflow: hidden;
    padding: 0;
    pointer-events: var(--ui-pointerEvents);
    position: absolute;
    right: 0;
    top: 0;
    /* width: calc(var(--right-sidebar-width) - var(--space-factor)*2); */
    width: calc(var(--right-sidebar-width)*2 - var(--space-factor));
    z-index: 5;
}

.excalidraw .library-unit {
    align-items: center;
    border: 1px solid transparent;
    border-radius: var(--border-radius-lg);
    box-sizing: content-box;
    display: flex;
    /* height: 155px; */
    height: 100%;
    justify-content: center;
    position: relative;
    /* width: 155px; */
    width: 100%;
}
```
