### ISSUE TITLE
Context menu items depend on user-agent/browser styles and some styles change unexpectedly

### ISSUE THREAD

**Issue by joaopalmeiro** [excalidraw/excalidraw#8469]
Hi! 👋 

I'm integrating Excalidraw into a React + Tailwind CSS project, and noticed that some of the context menu styles have changed:

|Before (no Tailwind CSS)|After (w/ Tailwind CSS)|
|-|-|
|<img width="1582" alt="Screenshot 2024-09-05 at 16 02 33" src="https://github.com/user-attachments/assets/a7f14223-32b0-48b7-92f8-1294048d23da">|<img width="1582" alt="Screenshot 2024-09-05 at 15 59 00" src="https://github.com/user-attachments/assets/b63cb3bb-0a2d-4bef-8ad7-2055a728952f">|

The styles that changed were the `font-size` of the label of each context menu item, as well as the `margin` of the separators/horizontal rules. They follow the user-agent/browser stylesheet.

If I'm correct, this change was due to Tailwind's [Preflight](https://tailwindcss.com/docs/preflight)/CSS reset and the fact that the [context menu](https://github.com/excalidraw/excalidraw/blob/51ea184938d57637faa345de85028aa8a0930ed2/packages/excalidraw/components/ContextMenu.tsx#L28-L128) items do not have styles defined for the font size and margin of the previously mentioned elements:

https://github.com/excalidraw/excalidraw/blob/51ea184938d57637faa345de85028aa8a0930ed2/packages/excalidraw/components/ContextMenu.scss#L22-L62

https://github.com/excalidraw/excalidraw/blob/51ea184938d57637faa345de85028aa8a0930ed2/packages/excalidraw/components/ContextMenu.scss#L94-L97

Therefore, to facilitate integrating Excalidraw with other technologies, I believe it would be beneficial to define specific styles (`font-size` and `margin`) for `.context-menu-item` (or `.context-menu-item__label`) and for `.context-menu-item-separator`. The [dropdown menu](https://github.com/excalidraw/excalidraw/tree/51ea184938d57637faa345de85028aa8a0930ed2/packages/excalidraw/components/dropdownMenu) and the context menu itself could serve as a basis for defining these values.

Let me know what you think and if I can open a PR, please. Thanks!

## Current workaround

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

/**
 * Revert the following Excalidraw styles to prevent Preflight/Tailwind CSS from
 * changing the defaults:
 */

.context-menu-item {
  font-size: revert;
}

.context-menu-item-separator {
  margin: revert;
}
```
