### ISSUE TITLE
Colors of the image are slightly different in dark mode

### ISSUE THREAD

**Issue by blackosinter** [excalidraw/excalidraw#9704]
The colors of images in Dark Mode appear muted and not as vibrant as in Light Mode.

![Image](https://github.com/user-attachments/assets/e7b19cc3-160a-4937-aeaa-cf6fadc1761f)

![Image](https://github.com/user-attachments/assets/582bea15-b687-4599-b97a-db941da04331)

**Comment by DudeThatsErin** [comment]
That's a known thing. It is inverting the colors of images in dark mode. No way to solve because of how Excalidraw handles dark mode.

**Comment by eliandoran** [comment]
I was able to work around this issue simply by adjusting the filter via CSS:

```css
.excalidraw.theme--dark canvas {
    --theme-filter: invert(100%) hue-rotate(180deg);
}
```
